### ISSUE TITLE
m & (n - 1) doesn't seem to work as m % (pow(2, n))

### ISSUE THREAD

**Issue by calebsander** [keonkim/awesome-bits#13]
I assume "Modulo 2<sup>n</sup> against m" means `m % (pow(2, n))`. In that case, for `m=11` and `n = 3`, `m & (n - 1)` gives `2`, but `11 % 8` gives `3`. Perhaps you mean `m & ((1 << n) - 1)`?

**Comment by xmikus01** [comment]
You are right, closed by #18.

**Comment by keon** [comment]
Thanks guys.
I am closing this issue since it is solved.
